# Generated by Django 3.2.13 on 2022-05-22 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lycee', '0005_presence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presence',
            name='dateOfCall',
            field=models.DateField(default=datetime.datetime(2022, 5, 22, 20, 44, 27, 24541), verbose_name='Date of Call'),
        ),
    ]
